apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterMultilineParser
metadata:
  name: multiline-java-log4j2-json
  labels:
    fluentbit.fluent.io/enabled: "true"
spec:
  type: regex
  parser: json
  keyContent: log
  flushTimeout: 5000
  rules:
    - start: "start_state"
      regex: '/^\{.*/'
      next: "cont"
    - start: "cont"
      regex: '/^[^\{].*/'
      next: "cont"
