#!/usr/bin/env bash
# Install Grafana dashboards as ConfigMaps. The kube-prometheus-stack Grafana
# sidecar auto-loads any ConfigMap with the label `grafana_dashboard=1`.
# Re-run this script after editing dashboards.yaml; sidecar will pick up the
# change within ~30s.
set -euo pipefail

CTX="${CTX:-minikube-remote}"

cd "$(dirname "$0")"

kubectl --context="$CTX" apply -f dashboards.yaml

cat <<EOF

Done. Dashboards (Grafana → Dashboards → Browse):
  - Load Test • Overview              (uid: lt-overview)
  - Load Test • OpenSearch (OS-01/02) (uid: lt-opensearch)
  - Load Test • Fluent-bit (FB)       (uid: lt-fluent-bit)
  - Load Test • Prometheus (PR)       (uid: lt-prometheus)
  - Load Test • node-exporter (NE)    (uid: lt-node-exporter)
  - Load Test • kube-state-metrics (KSM) (uid: lt-ksm)

Source: dashboards.yaml is generated by gen.py. Edit panels in gen.py and re-run:
  python3 gen.py > dashboards.yaml
  bash install.sh

EOF
