apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensearch-pv-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  hostPath:
    path: /data/opensearch
    type: DirectoryOrCreate
  claimRef:
    namespace: logging
    name: opensearch-cluster-master-opensearch-cluster-master-0
